### ISSUE TITLE
simulator download link is not working

### ISSUE THREAD

**Issue by khm159** [DIDS-EI/LLM-OBTEA#1]
It's seems to be the download URL is currently not working.

**Comment by DIDS-EI** [comment]
Thank you for bringing this to our attention. We have updated the download URL. Please try accessing it again using the link below:  https://drive.google.com/file/d/1ayAQZbPOyQV2W-V_ZdYv6AoqLOg0zvm1/view

**Comment by khm159** [comment]
Thank you very much!
I wish you the best of luck with everything
